# -*- coding: utf-8 -*-
"""Default overnight source registry."""

from __future__ import annotations

from src.overnight.types import SourceDefinition

_DEFAULT_SOURCES: tuple[SourceDefinition, ...] = (
    SourceDefinition(
        source_id="whitehouse_news",
        display_name="White House News",
        organization_type="official_policy",
        source_class="policy",
        entry_type="section_page",
        entry_urls=(
            "https://www.whitehouse.gov/news/",
            "https://www.whitehouse.gov/briefing-room/",
        ),
        priority=100,
        poll_interval_seconds=300,
        is_mission_critical=True,
        coverage_tier="official_policy",
        region_focus="US policy",
        coverage_focus="盯白宫政策声明、行政动作和事实清单，捕捉对贸易、制裁和产业政策的第一手信号。",
    ),
    SourceDefinition(
        source_id="fed_news",
        display_name="Federal Reserve News",
        organization_type="official_policy",
        source_class="policy",
        entry_type="rss",
        entry_urls=("https://www.federalreserve.gov/feeds/press_all.xml",),
        priority=100,
        poll_interval_seconds=300,
        is_mission_critical=True,
        coverage_tier="official_policy",
        region_focus="US rates",
        coverage_focus="盯联储新闻、声明和讲话，直接决定全球利率预期与成长风格压力。",
    ),
    SourceDefinition(
        source_id="ustr_press_releases",
        display_name="USTR Press Releases",
        organization_type="official_policy",
        source_class="policy",
        entry_type="section_page",
        entry_urls=(
            "https://ustr.gov/about-us/policy-offices/press-office/press-releases",
            "https://ustr.gov/about-us/policy-offices/press-office/speeches-and-remarks",
        ),
        priority=100,
        poll_interval_seconds=300,
        is_mission_critical=True,
        coverage_tier="official_policy",
        region_focus="US trade policy",
        coverage_focus="盯关税、贸易摩擦和供应链政策，是 A 股自主可控、航运和出口链的关键上游。",
    ),
    SourceDefinition(
        source_id="treasury_press_releases",
        display_name="Treasury Press Releases",
        organization_type="official_policy",
        source_class="policy",
        entry_type="section_page",
        entry_urls=("https://home.treasury.gov/news/press-releases",),
        priority=95,
        poll_interval_seconds=600,
        is_mission_critical=True,
        coverage_tier="official_policy",
        region_focus="US fiscal and sanctions",
        coverage_focus="盯财政部融资、制裁和国际金融政策，补齐贸易之外的政策冲击源。",
    ),
    SourceDefinition(
        source_id="bls_news_releases",
        display_name="BLS News Releases",
        organization_type="official_data",
        source_class="macro",
        entry_type="section_page",
        entry_urls=("https://www.bls.gov/bls/news-release/home.htm",),
        priority=40,
        poll_interval_seconds=1800,
        is_mission_critical=True,
        coverage_tier="official_data",
        region_focus="US macro",
        coverage_focus="盯 CPI、PPI、就业等官方数据原文，是利率预期和大宗链定价的上游。",
    ),
    SourceDefinition(
        source_id="bls_release_schedule",
        display_name="BLS Release Schedule",
        organization_type="official_data",
        source_class="calendar",
        entry_type="calendar_page",
        entry_urls=("https://www.bls.gov/schedule/news_release/",),
        priority=35,
        poll_interval_seconds=86400,
        is_mission_critical=True,
        coverage_tier="official_data",
        region_focus="US macro",
        coverage_focus="盯发布时间表，避免把未发布预期误当成已落地事实。",
    ),
    SourceDefinition(
        source_id="bea_news",
        display_name="BEA News",
        organization_type="official_data",
        source_class="macro",
        entry_type="section_page",
        entry_urls=("https://www.bea.gov/news/current-releases",),
        priority=85,
        poll_interval_seconds=3600,
        is_mission_critical=False,
        coverage_tier="official_data",
        region_focus="US macro",
        coverage_focus="补充 GDP、PCE、贸易与国际收支口径，帮助判断增长和通胀链条。",
    ),
    SourceDefinition(
        source_id="eia_pressroom",
        display_name="EIA Pressroom",
        organization_type="official_data",
        source_class="macro",
        entry_type="rss",
        entry_urls=("https://www.eia.gov/rss/press_rss.xml",),
        priority=82,
        poll_interval_seconds=3600,
        is_mission_critical=False,
        coverage_tier="official_data",
        region_focus="Energy markets",
        coverage_focus="补充油气、电力和能源供需叙事，服务原油、化工和运输成本线判断。",
    ),
    SourceDefinition(
        source_id="reuters_topics",
        display_name="Reuters Topics",
        organization_type="wire_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=("https://reutersbest.com/topic/",),
        priority=30,
        poll_interval_seconds=600,
        is_mission_critical=True,
        coverage_tier="editorial_media",
        region_focus="Global markets",
        coverage_focus="补充跨市场快讯和资产定价叙事，作为官方原文之外的第一层媒体确认。",
    ),
    SourceDefinition(
        source_id="ap_politics",
        display_name="AP Politics",
        organization_type="wire_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=("https://apnews.com/politics",),
        priority=75,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        region_focus="US policy",
        coverage_focus="补充美国政治进程和执行细节，帮助识别政策 headline 的二次发酵。",
    ),
    SourceDefinition(
        source_id="ap_business",
        display_name="AP Business",
        organization_type="wire_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=("https://apnews.com/business",),
        priority=70,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        region_focus="Global business",
        coverage_focus="补充产业、企业和宏观商业快讯，增强官方数据之外的上下游语境。",
    ),
    SourceDefinition(
        source_id="cnbc_world",
        display_name="CNBC World",
        organization_type="editorial_media",
        source_class="market",
        entry_type="rss",
        entry_urls=("https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100727362",),
        priority=78,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        region_focus="Global markets",
        coverage_focus="补充全球市场 headline 流，用于观察 overnight 风险偏好和板块共振方向。",
    ),
)


def build_default_source_registry(source_class: str | None = None) -> list[SourceDefinition]:
    if source_class is None:
        return list(_DEFAULT_SOURCES)
    return [source for source in _DEFAULT_SOURCES if source.source_class == source_class]
