# -*- coding: utf-8 -*-
"""Default overnight source registry."""

from __future__ import annotations

from app.sources.types import SourceDefinition

_DEFAULT_SOURCES: tuple[SourceDefinition, ...] = (
    SourceDefinition(
        source_id="whitehouse_news",
        display_name="White House News",
        organization_type="official_policy",
        source_class="policy",
        entry_type="section_page",
        entry_urls=(
            "https://www.whitehouse.gov/news/",
            "https://www.whitehouse.gov/briefing-room/",
        ),
        priority=100,
        poll_interval_seconds=300,
        is_mission_critical=True,
        coverage_tier="official_policy",
        source_group="official_policy",
        source_tier="P0",
        content_mode="policy",
        asset_tags=("rates", "trade", "technology", "energy"),
        mainline_tags=(
            "rates_liquidity",
            "trade_export_control",
            "tech_semiconductor",
            "geopolitics_energy",
        ),
        region_focus="US policy",
        coverage_focus="盯白宫政策声明、行政动作和事实清单，捕捉对贸易、制裁和产业政策的第一手信号。",
        allowed_domains=("whitehouse.gov",),
        search_discovery_enabled=True,
        search_queries=(
            'site:whitehouse.gov "fact sheet" White House tariffs trade semiconductor energy',
            'site:whitehouse.gov "presidential action" White House tariffs investment energy trade',
        ),
    ),
    SourceDefinition(
        source_id="fed_news",
        display_name="Federal Reserve News",
        organization_type="official_policy",
        source_class="policy",
        entry_type="rss",
        entry_urls=("https://www.federalreserve.gov/feeds/press_all.xml",),
        priority=100,
        poll_interval_seconds=300,
        is_mission_critical=True,
        coverage_tier="official_policy",
        source_group="official_policy",
        source_tier="P0",
        content_mode="rates",
        asset_tags=("rates", "usd", "technology", "equities"),
        mainline_tags=("rates_liquidity", "macro_data", "tech_semiconductor"),
        region_focus="US rates",
        coverage_focus="盯联储新闻、声明和讲话，直接决定全球利率预期与成长风格压力。",
        allowed_domains=("federalreserve.gov",),
    ),
    SourceDefinition(
        source_id="newyorkfed_news",
        display_name="New York Fed News",
        organization_type="official_data",
        source_class="macro",
        entry_type="section_page",
        entry_urls=("https://www.newyorkfed.org/newsevents/news",),
        priority=94,
        poll_interval_seconds=1800,
        is_mission_critical=False,
        coverage_tier="official_data",
        source_group="official_data",
        source_tier="P1",
        content_mode="rates",
        asset_tags=("rates", "usd", "equities", "gold"),
        mainline_tags=("rates_liquidity", "macro_data", "precious_metals_safe_haven"),
        region_focus="US rates and financial conditions",
        coverage_focus="盯纽约联储的市场操作、通胀预期和金融环境更新，补强联储 press feed 之外的细颗粒度事实。",
        allowed_domains=("newyorkfed.org",),
        search_discovery_enabled=True,
        search_queries=(
            'site:newyorkfed.org/newsevents/news "New York Fed" inflation expectations markets',
            'site:newyorkfed.org/newsevents/news "New York Fed" survey markets sofr fx',
        ),
    ),
    SourceDefinition(
        source_id="ustr_press_releases",
        display_name="USTR Press Releases",
        organization_type="official_policy",
        source_class="policy",
        entry_type="section_page",
        entry_urls=(
            "https://ustr.gov/about-us/policy-offices/press-office/press-releases",
            "https://ustr.gov/about-us/policy-offices/press-office/speeches-and-remarks",
        ),
        priority=100,
        poll_interval_seconds=300,
        is_mission_critical=True,
        coverage_tier="official_policy",
        source_group="official_policy",
        source_tier="P0",
        content_mode="trade",
        asset_tags=("trade", "shipping", "technology", "industrials"),
        mainline_tags=("trade_export_control", "shipping_logistics", "tech_semiconductor"),
        region_focus="US trade policy",
        coverage_focus="盯关税、贸易摩擦和供应链政策，是 A 股自主可控、航运和出口链的关键上游。",
        allowed_domains=("ustr.gov",),
        search_discovery_enabled=True,
        search_queries=(
            "site:ustr.gov/about/policy-offices/press-office/press-releases USTR press release tariffs supply chain",
            "site:ustr.gov tariffs china ustr press release",
        ),
    ),
    SourceDefinition(
        source_id="treasury_press_releases",
        display_name="Treasury Press Releases",
        organization_type="official_policy",
        source_class="policy",
        entry_type="section_page",
        entry_urls=("https://home.treasury.gov/news/press-releases",),
        priority=95,
        poll_interval_seconds=600,
        is_mission_critical=True,
        coverage_tier="official_policy",
        source_group="official_policy",
        source_tier="P0",
        content_mode="sanctions",
        asset_tags=("rates", "usd", "gold", "shipping"),
        mainline_tags=("rates_liquidity", "shipping_logistics", "precious_metals_safe_haven"),
        region_focus="US fiscal and sanctions",
        coverage_focus="盯财政部融资、制裁和国际金融政策，补齐贸易之外的政策冲击源。",
        allowed_domains=("treasury.gov",),
        search_discovery_enabled=True,
        search_queries=("site:home.treasury.gov/news/press-releases Treasury press release sanctions financing",),
    ),
    SourceDefinition(
        source_id="census_economic_indicators",
        display_name="Census Economic Indicators",
        organization_type="official_data",
        source_class="macro",
        entry_type="rss",
        entry_urls=("https://www.census.gov/economic-indicators/indicator.xml",),
        priority=92,
        poll_interval_seconds=1800,
        is_mission_critical=True,
        coverage_tier="official_data",
        source_group="commodity_data",
        source_tier="P1",
        content_mode="macro",
        asset_tags=("rates", "usd", "shipping", "industrials"),
        mainline_tags=("macro_data", "rates_liquidity", "shipping_logistics"),
        region_focus="US macro",
        coverage_focus="补充零售、贸易、库存、新屋销售等官方指标发布，填补 BLS 不稳定时的美国数据层空缺。",
        allowed_domains=("census.gov",),
    ),
    SourceDefinition(
        source_id="bls_news_releases",
        display_name="BLS News Releases",
        organization_type="official_data",
        source_class="macro",
        entry_type="section_page",
        entry_urls=("https://www.bls.gov/bls/news-release/home.htm",),
        priority=40,
        poll_interval_seconds=1800,
        is_mission_critical=True,
        coverage_tier="official_data",
        source_group="official_policy",
        source_tier="P0",
        content_mode="macro",
        asset_tags=("rates", "usd", "gold", "equities"),
        mainline_tags=("macro_data", "rates_liquidity", "precious_metals_safe_haven"),
        region_focus="US macro",
        coverage_focus="盯 CPI、PPI、就业等官方数据原文，是利率预期和大宗链定价的上游。",
        allowed_domains=("bls.gov",),
        search_discovery_enabled=True,
        search_queries=(
            "site:bls.gov/news.release Employment Situation CPI PPI payrolls unemployment BLS",
            "site:bls.gov/news.release import export prices productivity real earnings BLS",
        ),
    ),
    SourceDefinition(
        source_id="bls_release_schedule",
        display_name="BLS Release Schedule",
        organization_type="official_data",
        source_class="calendar",
        entry_type="calendar_page",
        entry_urls=("https://www.bls.gov/schedule/news_release/",),
        priority=35,
        poll_interval_seconds=86400,
        is_mission_critical=True,
        coverage_tier="official_data",
        source_group="commodity_data",
        source_tier="P1",
        content_mode="macro",
        asset_tags=("rates", "usd"),
        mainline_tags=("macro_data", "rates_liquidity"),
        region_focus="US macro",
        coverage_focus="盯发布时间表，避免把未发布预期误当成已落地事实。",
        allowed_domains=("bls.gov",),
    ),
    SourceDefinition(
        source_id="bea_news",
        display_name="BEA News",
        organization_type="official_data",
        source_class="macro",
        entry_type="section_page",
        entry_urls=("https://www.bea.gov/news/current-releases",),
        priority=85,
        poll_interval_seconds=3600,
        is_mission_critical=False,
        coverage_tier="official_data",
        source_group="official_data",
        source_tier="P1",
        content_mode="macro",
        asset_tags=("rates", "usd", "shipping", "industrials"),
        mainline_tags=("macro_data", "rates_liquidity", "shipping_logistics"),
        region_focus="US macro",
        coverage_focus="补充 GDP、PCE、贸易与国际收支口径，帮助判断增长和通胀链条。",
        allowed_domains=("bea.gov",),
    ),
    SourceDefinition(
        source_id="ecb_press",
        display_name="ECB Press",
        organization_type="official_data",
        source_class="macro",
        entry_type="rss",
        entry_urls=("https://www.ecb.europa.eu/rss/press.html",),
        priority=88,
        poll_interval_seconds=3600,
        is_mission_critical=False,
        coverage_tier="official_data",
        source_group="official_data",
        source_tier="P1",
        content_mode="rates",
        asset_tags=("rates", "usd", "gold", "equities"),
        mainline_tags=("rates_liquidity", "macro_data", "precious_metals_safe_haven"),
        region_focus="Europe rates",
        coverage_focus="盯欧洲央行 press、讲话和发布，补足全球利率、汇率与风险偏好的海外政策语境。",
        allowed_domains=("ecb.europa.eu",),
    ),
    SourceDefinition(
        source_id="worldbank_news",
        display_name="World Bank News",
        organization_type="official_data",
        source_class="macro",
        entry_type="section_page",
        entry_urls=("https://www.worldbank.org/en/news",),
        priority=74,
        poll_interval_seconds=3600,
        is_mission_critical=False,
        coverage_tier="official_data",
        source_group="official_data",
        source_tier="P2",
        content_mode="macro",
        asset_tags=("rates", "usd", "shipping", "industrials"),
        mainline_tags=("macro_data", "rates_liquidity", "shipping_logistics"),
        region_focus="Global growth and development",
        coverage_focus="补全球增长、贸易融资、能源和粮食安全等跨国机构口径，帮助理解宏观与商品链的外部环境。",
        allowed_domains=("worldbank.org",),
        search_discovery_enabled=True,
        search_queries=(
            'site:worldbank.org/en/news "World Bank" trade growth commodity energy',
            'site:worldbank.org/en/news "World Bank" press release global economy shipping',
        ),
    ),
    SourceDefinition(
        source_id="eia_pressroom",
        display_name="EIA Pressroom",
        organization_type="official_data",
        source_class="macro",
        entry_type="rss",
        entry_urls=("https://www.eia.gov/rss/press_rss.xml",),
        priority=82,
        poll_interval_seconds=3600,
        is_mission_critical=False,
        coverage_tier="official_data",
        source_group="commodity_data",
        source_tier="P1",
        content_mode="energy",
        asset_tags=("oil", "natural_gas", "chemicals", "shipping"),
        mainline_tags=("geopolitics_energy", "industrials_chemicals", "shipping_logistics"),
        region_focus="Energy markets",
        coverage_focus="补充油气、电力和能源供需叙事，服务原油、化工和运输成本线判断。",
        allowed_domains=("eia.gov",),
    ),
    SourceDefinition(
        source_id="iea_news",
        display_name="IEA News",
        organization_type="official_data",
        source_class="macro",
        entry_type="section_page",
        entry_urls=("https://www.iea.org/news",),
        priority=87,
        poll_interval_seconds=3600,
        is_mission_critical=False,
        coverage_tier="official_data",
        source_group="commodity_data",
        source_tier="P1",
        content_mode="energy",
        asset_tags=("oil", "natural_gas", "power", "chemicals"),
        mainline_tags=("geopolitics_energy", "industrials_chemicals", "shipping_logistics"),
        region_focus="Global energy markets",
        coverage_focus="盯 IEA 对油气、库存释放、能源安全和关键矿物供应链的更新，补强原油与化工主线。",
        allowed_domains=("iea.org",),
        search_discovery_enabled=True,
        search_queries=(
            'site:iea.org/news IEA oil supply disruption strategic stocks',
            'site:iea.org/news IEA energy security minerals supply chain',
        ),
    ),
    SourceDefinition(
        source_id="cftc_general_press_releases",
        display_name="CFTC General Press Releases",
        organization_type="official_policy",
        source_class="policy",
        entry_type="rss",
        entry_urls=("https://www.cftc.gov/RSS/RSSGP/rssgp.xml",),
        priority=84,
        poll_interval_seconds=1800,
        is_mission_critical=False,
        coverage_tier="official_policy",
        source_group="commodity_data",
        source_tier="P1",
        content_mode="commodities",
        asset_tags=("oil", "gold", "agriculture", "crypto"),
        mainline_tags=("geopolitics_energy", "precious_metals_safe_haven", "industrials_chemicals"),
        region_focus="US derivatives regulation",
        coverage_focus="盯商品、期货、清算和预测市场监管更新，为原油、贵金属、农产品和衍生品链补监管信号。",
        allowed_domains=("cftc.gov",),
    ),
    SourceDefinition(
        source_id="cftc_enforcement_press_releases",
        display_name="CFTC Enforcement Press Releases",
        organization_type="official_policy",
        source_class="policy",
        entry_type="rss",
        entry_urls=("https://www.cftc.gov/RSS/RSSENF/rssenf.xml",),
        priority=81,
        poll_interval_seconds=1800,
        is_mission_critical=False,
        coverage_tier="official_policy",
        source_group="commodity_data",
        source_tier="P1",
        content_mode="commodities",
        asset_tags=("oil", "gold", "agriculture", "crypto"),
        mainline_tags=("geopolitics_energy", "precious_metals_safe_haven", "industrials_chemicals"),
        region_focus="US derivatives enforcement",
        coverage_focus="盯 CFTC 执法通报和处罚案例，补充商品、加密和场外衍生品的风险外溢信号。",
        allowed_domains=("cftc.gov",),
    ),
    SourceDefinition(
        source_id="cftc_speeches_testimony",
        display_name="CFTC Speeches and Testimony",
        organization_type="official_policy",
        source_class="policy",
        entry_type="rss",
        entry_urls=("https://www.cftc.gov/RSS/RSSST/rssst.xml",),
        priority=72,
        poll_interval_seconds=3600,
        is_mission_critical=False,
        coverage_tier="official_policy",
        source_group="commodity_data",
        source_tier="P2",
        content_mode="commodities",
        asset_tags=("oil", "gold", "agriculture", "crypto"),
        mainline_tags=("geopolitics_energy", "precious_metals_safe_haven", "industrials_chemicals"),
        region_focus="US derivatives policy remarks",
        coverage_focus="补充 CFTC 主席和委员对商品、加密和市场结构的口径变化，帮助识别监管预期变化。",
        allowed_domains=("cftc.gov",),
    ),
    SourceDefinition(
        source_id="bis_news_updates",
        display_name="BIS News Updates",
        organization_type="official_policy",
        source_class="policy",
        entry_type="section_page",
        entry_urls=("https://media.bis.gov/news-updates",),
        priority=97,
        poll_interval_seconds=600,
        is_mission_critical=True,
        coverage_tier="official_policy",
        source_group="official_policy",
        source_tier="P0",
        content_mode="technology",
        asset_tags=("technology", "semiconductors", "trade", "industrials"),
        mainline_tags=("trade_export_control", "tech_semiconductor"),
        region_focus="US export control",
        coverage_focus="盯美国商务部工业安全局的出口管制、实体清单和半导体设备限制更新。",
        allowed_domains=("bis.gov",),
    ),
    SourceDefinition(
        source_id="ofac_recent_actions",
        display_name="OFAC Recent Actions",
        organization_type="official_policy",
        source_class="policy",
        entry_type="section_page",
        entry_urls=("https://ofac.treasury.gov/recent-actions",),
        priority=96,
        poll_interval_seconds=600,
        is_mission_critical=True,
        coverage_tier="official_policy",
        source_group="official_policy",
        source_tier="P0",
        content_mode="sanctions",
        asset_tags=("oil", "shipping", "gold", "usd"),
        mainline_tags=("trade_export_control", "shipping_logistics", "precious_metals_safe_haven"),
        region_focus="US sanctions",
        coverage_focus="盯 OFAC 最新制裁行动和许可变化，直接映射航运、能源、贵金属和跨境结算风险。",
        allowed_domains=("ofac.treasury.gov", "treasury.gov"),
        search_discovery_enabled=True,
        search_queries=(
            "site:ofac.treasury.gov/recent-actions OFAC recent actions sanctions general license FAQ",
            "site:ofac.treasury.gov/recent-actions OFAC sanctions advisory designation removal",
        ),
    ),
    SourceDefinition(
        source_id="state_spokesperson_releases",
        display_name="State Department Briefings and Statements",
        organization_type="official_policy",
        source_class="policy",
        entry_type="section_page",
        entry_urls=("https://www.state.gov/briefings-statements/",),
        priority=90,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="official_policy",
        source_group="official_policy",
        source_tier="P0",
        content_mode="diplomacy",
        asset_tags=("oil", "shipping", "gold", "technology"),
        mainline_tags=("trade_export_control", "geopolitics_energy", "shipping_logistics"),
        region_focus="US diplomacy",
        coverage_focus="盯国务院口径变化，补充关税谈判、制裁协调与地缘摩擦的官方外交表述。",
        allowed_domains=("state.gov",),
        is_enabled=False,
        disable_reason="User-directed stop: do not pull State Department sources in this project.",
    ),
    SourceDefinition(
        source_id="dod_news_releases",
        display_name="Department of Defense News Releases",
        organization_type="official_policy",
        source_class="policy",
        entry_type="section_page",
        entry_urls=("https://www.defense.gov/News/Releases/",),
        priority=88,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="official_policy",
        source_group="official_policy",
        source_tier="P0",
        content_mode="defense",
        asset_tags=("oil", "shipping", "defense", "technology"),
        mainline_tags=("geopolitics_energy", "shipping_logistics", "tech_semiconductor"),
        region_focus="US defense posture",
        coverage_focus="盯五角大楼行动、部署与声明，捕捉对能源运输、军工和地缘风险偏好的冲击。",
        allowed_domains=("defense.gov",),
        is_enabled=False,
        disable_reason="User-directed stop: do not pull Department of Defense sources in this project.",
    ),
    SourceDefinition(
        source_id="doe_articles",
        display_name="Department of Energy Articles",
        organization_type="official_policy",
        source_class="policy",
        entry_type="section_page",
        entry_urls=("https://www.energy.gov/news/",),
        priority=86,
        poll_interval_seconds=1800,
        is_mission_critical=False,
        coverage_tier="official_policy",
        source_group="commodity_data",
        source_tier="P0",
        content_mode="energy",
        asset_tags=("oil", "natural_gas", "power", "uranium"),
        mainline_tags=("geopolitics_energy", "industrials_chemicals", "tech_semiconductor"),
        region_focus="US energy policy",
        coverage_focus="盯能源部对油气、电网、核能和能源技术的政策动作，补齐能源与制造链联动。",
        allowed_domains=("energy.gov",),
        search_discovery_enabled=True,
        search_queries=(
            "site:energy.gov/articles Department of Energy loan office energy dominance financing loan commitment",
            "site:energy.gov/articles Department of Energy strategic petroleum reserve power grid battery manufacturing",
            "site:energy.gov/articles Department of Energy LNG grid coal reliability manufacturing",
        ),
    ),
    SourceDefinition(
        source_id="reuters_topics",
        display_name="Reuters Topics",
        organization_type="wire_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=(
            "https://reutersbest.com/topic/commodities-energy/",
            "https://reutersbest.com/topic/economics-central-banking/",
            "https://reutersbest.com/topic/equities/",
            "https://reutersbest.com/topic/markets/",
            "https://reutersbest.com/topic/politics-general/",
        ),
        priority=30,
        poll_interval_seconds=600,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="market_media",
        source_tier="P1",
        content_mode="market",
        asset_tags=("rates", "oil", "technology", "shipping"),
        mainline_tags=("rates_liquidity", "trade_export_control", "geopolitics_energy", "tech_semiconductor"),
        region_focus="Global markets",
        coverage_focus="补充跨市场快讯和资产定价叙事，作为官方原文之外的第一层媒体确认。",
        allowed_domains=("reutersbest.com",),
    ),
    SourceDefinition(
        source_id="ap_politics",
        display_name="AP Politics",
        organization_type="wire_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=("https://apnews.com/politics",),
        priority=75,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="market_media",
        source_tier="P2",
        content_mode="policy",
        asset_tags=("rates", "trade", "oil", "gold"),
        mainline_tags=("trade_export_control", "geopolitics_energy", "precious_metals_safe_haven"),
        region_focus="US policy",
        coverage_focus="补充美国政治进程和执行细节，帮助识别政策 headline 的二次发酵。",
        allowed_domains=("apnews.com",),
    ),
    SourceDefinition(
        source_id="ap_business",
        display_name="AP Business",
        organization_type="wire_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=("https://apnews.com/business",),
        priority=70,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="market_media",
        source_tier="P2",
        content_mode="market",
        asset_tags=("equities", "oil", "shipping", "industrials"),
        mainline_tags=("macro_data", "geopolitics_energy", "shipping_logistics", "industrials_chemicals"),
        region_focus="Global business",
        coverage_focus="补充产业、企业和宏观商业快讯，增强官方数据之外的上下游语境。",
        allowed_domains=("apnews.com",),
    ),
    SourceDefinition(
        source_id="ap_world",
        display_name="AP World",
        organization_type="wire_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=("https://apnews.com/world-news",),
        priority=72,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="market_media",
        source_tier="P2",
        content_mode="policy",
        asset_tags=("oil", "gold", "shipping", "equities"),
        mainline_tags=("geopolitics_energy", "shipping_logistics", "precious_metals_safe_haven"),
        region_focus="Global geopolitics",
        coverage_focus="补全球地缘政治和冲突进展，帮助识别油价、金价和航运风险的跨市场传导。",
        allowed_domains=("apnews.com",),
    ),
    SourceDefinition(
        source_id="ap_technology",
        display_name="AP Technology",
        organization_type="wire_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=("https://apnews.com/technology",),
        priority=69,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="market_media",
        source_tier="P2",
        content_mode="technology",
        asset_tags=("technology", "semiconductors", "equities", "trade"),
        mainline_tags=("tech_semiconductor", "trade_export_control"),
        region_focus="Global technology",
        coverage_focus="补 AI、芯片、平台监管与科技供应链新闻，增强美股科技股与 A 股映射判断。",
        allowed_domains=("apnews.com",),
    ),
    SourceDefinition(
        source_id="ap_economy",
        display_name="AP Economy",
        organization_type="wire_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=("https://apnews.com/hub/economy",),
        priority=71,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="market_media",
        source_tier="P2",
        content_mode="macro",
        asset_tags=("rates", "usd", "equities", "oil"),
        mainline_tags=("macro_data", "rates_liquidity", "geopolitics_energy"),
        region_focus="Global macro",
        coverage_focus="补就业、增长、通胀和政策外溢报道，增强对美股收盘归因的媒体确认层。",
        allowed_domains=("apnews.com",),
    ),
    SourceDefinition(
        source_id="ap_financial_markets",
        display_name="AP Financial Markets",
        organization_type="wire_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=("https://apnews.com/hub/financial-markets",),
        priority=74,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="market_media",
        source_tier="P2",
        content_mode="market",
        asset_tags=("equities", "rates", "oil", "gold"),
        mainline_tags=("rates_liquidity", "macro_data", "geopolitics_energy", "precious_metals_safe_haven"),
        region_focus="Cross-asset markets",
        coverage_focus="补股债汇金油的盘后联动叙事，服务中国早晨固定结论的市场归因层。",
        allowed_domains=("apnews.com",),
    ),
    SourceDefinition(
        source_id="kitco_news",
        display_name="Kitco News",
        organization_type="editorial_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=("https://www.kitco.com/news",),
        priority=80,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="commodity_data",
        source_tier="P2",
        content_mode="precious_metals",
        asset_tags=("gold", "silver", "usd", "rates"),
        mainline_tags=("precious_metals_safe_haven", "rates_liquidity", "macro_data"),
        region_focus="Precious metals markets",
        coverage_focus="补黄金、白银与实际利率驱动的 overnight 报道，服务贵金属和避险链解释层。",
        allowed_domains=("kitco.com",),
    ),
    SourceDefinition(
        source_id="oilprice_world_news",
        display_name="Oilprice World News",
        organization_type="editorial_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=("https://oilprice.com/Latest-Energy-News/World-News/",),
        priority=77,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="commodity_data",
        source_tier="P2",
        content_mode="energy",
        asset_tags=("oil", "natural_gas", "shipping", "equities"),
        mainline_tags=("geopolitics_energy", "industrials_chemicals", "shipping_logistics"),
        region_focus="Global energy markets",
        coverage_focus="补油气与能源地缘 headline，增强原油、化工和航运的跨市场语境层。",
        allowed_domains=("oilprice.com",),
    ),
    SourceDefinition(
        source_id="farmdoc_daily",
        display_name="farmdoc daily",
        organization_type="editorial_media",
        source_class="market",
        entry_type="section_page",
        entry_urls=("https://farmdocdaily.illinois.edu/",),
        priority=73,
        poll_interval_seconds=1800,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="commodity_data",
        source_tier="P2",
        content_mode="agriculture",
        asset_tags=("agriculture", "shipping", "industrials", "usd"),
        mainline_tags=("industrials_chemicals", "shipping_logistics", "macro_data"),
        region_focus="US agriculture and biofuels",
        coverage_focus="补农产品、乙醇、生物燃料和农业供需研究，覆盖中国期货映射所需的农化信息层。",
        allowed_domains=("farmdocdaily.illinois.edu",),
    ),
    SourceDefinition(
        source_id="cnbc_world",
        display_name="CNBC World",
        organization_type="editorial_media",
        source_class="market",
        entry_type="rss",
        entry_urls=("https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100727362",),
        priority=78,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="market_media",
        source_tier="P2",
        content_mode="market",
        asset_tags=("equities", "rates", "technology", "oil"),
        mainline_tags=("rates_liquidity", "geopolitics_energy", "tech_semiconductor", "macro_data"),
        region_focus="Global markets",
        coverage_focus="补充全球市场 headline 流，用于观察 overnight 风险偏好和板块共振方向。",
        allowed_domains=("cnbc.com",),
    ),
    SourceDefinition(
        source_id="cnbc_markets",
        display_name="CNBC Markets",
        organization_type="editorial_media",
        source_class="market",
        entry_type="rss",
        entry_urls=("https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114",),
        priority=79,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="market_media",
        source_tier="P2",
        content_mode="market",
        asset_tags=("equities", "rates", "technology", "oil"),
        mainline_tags=("rates_liquidity", "macro_data", "tech_semiconductor", "geopolitics_energy"),
        region_focus="US and global markets",
        coverage_focus="补充美股收盘归因、通胀、利率和板块轮动 headline，增强中国早晨对美股结果的直接解释层。",
        allowed_domains=("cnbc.com",),
    ),
    SourceDefinition(
        source_id="cnbc_technology",
        display_name="CNBC Technology",
        organization_type="editorial_media",
        source_class="market",
        entry_type="rss",
        entry_urls=("https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19854910",),
        priority=76,
        poll_interval_seconds=900,
        is_mission_critical=False,
        coverage_tier="editorial_media",
        source_group="market_media",
        source_tier="P2",
        content_mode="technology",
        asset_tags=("technology", "semiconductors", "equities", "trade"),
        mainline_tags=("tech_semiconductor", "trade_export_control", "macro_data"),
        region_focus="US technology sector",
        coverage_focus="补 AI、大模型、芯片和美股科技巨头 headline，服务科技股走强/走弱与 A 股映射判断。",
        allowed_domains=("cnbc.com",),
    ),
)


def build_default_source_registry(source_class: str | None = None, *, include_disabled: bool = False) -> list[SourceDefinition]:
    registry = list(_DEFAULT_SOURCES if include_disabled else [source for source in _DEFAULT_SOURCES if source.is_enabled])
    if source_class is None:
        return registry
    return [source for source in registry if source.source_class == source_class]
